#redis ≈‰÷√
spring:
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000
    database: 0
    redis:
      host: 127.0.0.1
      port: 6380
server:
  port: 8086
logging:
  path: classpath:log4j.properties